// pim_runtime.h — Flat C ABI for the MLIR-lowered PIM matmul dispatch.
//
// This header declares the single entry point that PimToRuntimeCallsPass
// generates calls to.  The implementation (in the backend shared library)
// is responsible for translating the flat arguments into a
// triton_pim_kernel_launch() call and managing DPU context lifecycle.
//
// Enum values must stay in sync with the TableGen definitions in
// include/triton-shared/Dialect/PIM/IR/PIMDialect.td.

#ifndef TRITON_SHARED_RUNTIME_PIM_RUNTIME_H
#define TRITON_SHARED_RUNTIME_PIM_RUNTIME_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// ---------------------------------------------------------------------------
// Enum mirrors for PIMDialect.td  (values must match the TableGen I32Enum)
// ---------------------------------------------------------------------------

typedef enum {
  PIM_SPLIT_UNKNOWN = 0,
  PIM_SPLIT_M       = 1,
  PIM_SPLIT_N       = 2,
  PIM_SPLIT_K       = 3,
} PimSplitAxis;

typedef enum {
  PIM_REUSE_UNKNOWN  = 0,
  PIM_STREAM_A       = 1,
  PIM_STREAM_B       = 2,
  PIM_REUSE_A        = 3,
  PIM_REUSE_B        = 4,
} PimReusePolicy;

typedef enum {
  PIM_REDUCTION_UNKNOWN       = 0,
  PIM_REDUCTION_HOST_REDUCE   = 1,
  PIM_REDUCTION_DPU_REDUCE    = 2,
  PIM_REDUCTION_ATOMIC_REDUCE = 3,
} PimReductionStrategy;

typedef enum {
  PIM_KERNEL_UNKNOWN = 0,
  PIM_KERNEL_FLAT    = 1,
  PIM_KERNEL_GROUPED = 2,
  PIM_KERNEL_TILED   = 3,
} PimKernelVariant;

typedef enum {
  PIM_PACK_UNKNOWN = 0,
  PIM_PACK_NONE    = 1,
  PIM_PACK_INT8    = 2,
  PIM_PACK_INT4    = 3,
} PimPackFormat;

typedef enum {
  PIM_ACCUM_UNKNOWN = 0,
  PIM_ACCUM_INT32   = 1,
  PIM_ACCUM_FLOAT32 = 2,
} PimAccumType;

typedef enum {
  PIM_WRITEBACK_UNKNOWN   = 0,
  PIM_WRITEBACK_DIRECT    = 1,
  PIM_WRITEBACK_SCATTERED = 2,
} PimWritebackMode;

// ---------------------------------------------------------------------------
// Entry point generated by PimToRuntimeCallsPass
//
// Pointers a / b / c are passed as int64_t (the result of
// memref.extract_aligned_pointer_as_index + arith.index_castui).
// All enum fields are passed as int32_t matching the TableGen I32Enum values.
// ---------------------------------------------------------------------------
void triton_pim_matmul(
    int64_t a,          // aligned base pointer of A (row-major, M×K)
    int64_t b,          // aligned base pointer of B (row-major, K×N)
    int64_t c,          // aligned base pointer of C (row-major, M×N)
    int64_t m,          // problem M dimension
    int64_t n,          // problem N dimension
    int64_t k,          // problem K dimension
    int64_t tile_m,     // DPU tile rows
    int64_t tile_n,     // DPU tile columns
    int64_t tile_k,     // DPU tile K depth
    int32_t split_axis,    // PimSplitAxis
    int32_t reuse_policy,  // PimReusePolicy
    int32_t reduction,     // PimReductionStrategy
    int32_t tasklets,      // tasklets per DPU
    int32_t active_dpus,   // number of DPUs to activate
    int32_t kernel_variant, // PimKernelVariant
    int32_t pack_format,    // PimPackFormat
    int32_t accum_type,     // PimAccumType
    int32_t writeback_mode, // PimWritebackMode
    int32_t alignment,      // transfer alignment in bytes
    int32_t group_m,        // GROUPED kernel row-group size (0 = not grouped)
    int32_t batch_count     // number of batches (1 for non-batched)
);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // TRITON_SHARED_RUNTIME_PIM_RUNTIME_H
